BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.3
            Button:
                id: button_up
                text: 'Up'
            Button:
                id: button_down
                text: 'Down'
    Button:
        id: converter
        text: 'Convert miles to km'
    Label:
        text: ''
